input: "test.jar"
output: "%name%.obf.jar"

transformers:
  renamers:
#    dictionary: "\\/_üöäÜÖÄ"
    length:  24
    classes: true  # Rename classes
    fields:  true  # Rename fields
    methods: false # Rename methods
#    localVariables: true  # Rename local variables
#    enums: FULL   # NONE = Don't rename enums, FULL = Rename enum, TO_STRING = Rename enum, but override the toString() call
#
#  removers:
#    lineNumbers: true
#    generics:    false
#
#  string: # More options?
#    enabled:    true
#    complexity: 2 # 1-5
#
  flow:
    enabled: true

    shuffleBlocks: true
    # size of instruction blocks
    # less = more obfuscation, not recommended to set lower than 3
    blockSizeMin: 4
    blockSizeMax: 6

    addFakeJumps: true
    fakeJumpChancePercent: 10
#    layers: 5 # 1-20, bigger the number the slower to obfuscate
#
#  minecraft:
#    removeOptifineObfIds: true # remove the CF___ thing in the fields optifine leaves behind
#
#  shuffler:
#    methods: false
#    fields: true
# ...
