name: Go Make

on:
  - push
  - pull_request
    
jobs:
  build:
    # if: "contains(github.event.head_commit.message, '[make]')"
    runs-on: alpine-latest

    steps:
    - uses: actions/checkout@v3
    - name: setup
      run: |
        apk add git make gcc go
    - name: Build
      run: |
        cd gui
        make build

