name: C/C++ Make

on:
  - push
  - pull_request
    
jobs:
  build:
    if: "contains(github.event.head_commit.message, '[make]')"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: cd
      run: |
        cd encryption
        chmod +x c.sh
        chmod +x cpp.sh
    - name: C
      run: ./c.sh
    - name: C++
      run: ./cpp.sh
    - name: cleanup
      run: make clean
  
