name: Java with Maven

on:
  - push
  - pull_request
 
defaults:
  run:
    shell: bash
    working-directory: obfuscator/

jobs:
  build:
    if: "contains(github.event.head_commit.message, '[maven]')"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: |
        mvn -B package --file pom.xml
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1.0.8
      with:
        name: Obfuscator-${{ github.sha }}
        path: target/*.jar
