name: Java with Maven

on:
  - push
  - pull_request
 
jobs:
  build:
    # if: "contains(github.event.head_commit.message, '[maven]')"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: |
        cd obfuscator
        mvn -B package --file pom.xml
    - name: move jar files to out directory
      run: |
        mkdir out
        mv obfuscator/target/*.jar out/
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1.0.8
      with:
        name: Obfuscator-${{ github.sha }}
        path: out/
      
